LOCAL_SETTINGS_DIR="/Users/$USER/mysettings"
LOCAL_BASHRC="$LOCAL_SETTINGS_DIR/bashrc"

export PATH=$PATH:~/misc/bin:~/bin

# Enable most man viewer if installed
#if command -v most > /dev/null 2>&1; then
#   export PAGER="most"
#fi

function currentGitBranch {
   # Pipe std err to dev/null and add leading and trailing brackets  
   git branch --show-current 2> /dev/null | sed 's/^/ \[/' | sed 's/$/\]/'
}

# Copy of ubuntu command prompt
export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\033[00;32m\]\$(currentGitBranch)\[\033[00m\]$ "

# Ignore case when tabbing in terminal
bind 'set completion-ignore-case on'

# Set the preferred editor
# NB! Non GUI systems does not have gvim (e.g. raspberry pi), then set it to vim
if [ "$(command -v gvim)" ]; then
   export EDITOR="gvim --nofork"
else
   export EDITOR="vim"
fi

# Aliases
alias ll='ls -alF'
alias less='less -R'
alias mem-by-proc="ps aux | head -1; ps aux | sort -rnk 4 | head -5"
alias find-large-files="du -ah | sort -rh | head -5"

# Local settings
if [ -f "$LOCAL_BASHRC" ]; then
   source "$LOCAL_BASHRC"
fi

function chruby-reload {
   RUBIES=(~/.rubies/*)
}
